linters:
  enable:
    - gci
    - revive
linters-settings:
  gci:
    sections:
      - standard # Captures all standard packages.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/marcuscaisey/golox) # Groups all imports with the specified Prefix.
    custom-order: true
issues:
  exclude-rules:
    - text: "indent-error-flow: if block ends with a return statement, so drop this else and outdent its block"
      linters:
        - revive
  include:
    - EXC0012 # revive: exported (.+) should have comment( \(or a comment on this block\))? or be unexported
    - EXC0013 # revive: package comment should be of the form "(.+)...
    - EXC0014 # revive: comment on exported (.+) should be of the form "(.+)..."
    - EXC0015 # revive: should have a package comment
